name: 'List test files'
description: 'Produce paired matrix of test-input files'
inputs:
  test-file-directory:
    description: 'Where the test files are located'
    required: true
  test-file-extension: 
    description: 'The extension of the test files (e.g. cwl ; not .cwl) '
    required: true
  inputs-file-extension: 
    description: 'The extension of the input manifest (to replace the extension of the test files, e.g. yml ; not .yml).'
    required: true
outputs:
  tests-matrix: ${{ steps.set-matrix.outputs.tests-matrix }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - id: set-matrix
    run: |
      echo "tests-matrix=$(ls ${{ inputs.test-file-directory }} /*.${{ inputs.test-file-extension }} | jq -R -s -c 'split("\n")[:-1] | map([., (sub("\\.${{ inputs.test-file-extension }}$"; ".${{ inputs.inputs-file-extenstion }}"))])')"  >> "$GITHUB_OUTPUT"
    shell: bash  
  - name: Show matrix
    shell: bash
    run: |
      echo ${{ steps.set-matrix.outputs.tests-matrix }}
